### ISSUE TITLE
readme needs more context

### ISSUE THREAD

**Issue by felafel** [popeen/Home-Assistant-Custom-Component-TCL-Remote#3]
I am new to home assistant.

I put this in the confi yaml -- 
"tcl_tv_remote:"

Where does the service text go?

How can I use it in HA?  Do I need to create something to use the service(s) or will it show up as a card?

Is there a web page that explains what the keys do?

Thanks

**Comment by felafel** [comment]
I saw another question you had and went to Developer Tools and then Services.  I assume this is for testing.

I put this in YAML mode and I get back a failure.  In UI mode the services show as available so I think this is registered correctly.

service: tcl_tv_remote.send_key
data:
  key: TR_KEY_POWER
  ip: 192.168.0.79
  port: 4123

Failed to call service .... Unknown Error.

Thanks in advance

**Comment by JMoratelli** [comment]
> I saw another question you had and went to Developer Tools and then Services. I assume this is for testing.
> 
> I put this in YAML mode and I get back a failure. In UI mode the services show as available so I think this is registered correctly.
> 
> service: tcl_tv_remote.send_key data: key: TR_KEY_POWER ip: 192.168.0.79 port: 4123
> 
> Failed to call service .... Unknown Error.
> 
> Thanks in advance

Same error here

**Comment by TrilIiard** [comment]
You need to add this to your configuration.yaml:

```
tcl_tv_remote:
```

Change the IP to the IP of your TV and the source to the one you like to have. Restart Home Assistent and you can use those Services within Home Assistent.

Working fine on my TCL 49DP600X1 

With this service you can do things like writing a script like this as a sleep timer:

```
alias: TV Standby
sequence:
  - delay:
      hours: 0
      minutes: 40
      seconds: 0
      milliseconds: 0
  - service: tcl_tv_remote.send_key
    data:
      key: TR_KEY_POWER
      ip: x.x.x.x
      port: 4123
mode: single
icon: mdi:television-off
```

Or make a button like this to turn your tv off directly and hold it for starting sleep timer script:

```
show_name: false
show_icon: true
type: button
tap_action:
  action: call-service
  service: tcl_tv_remote.send_key
  target: {}
  data:
    key: TR_KEY_POWER
    ip: x.x.x.x
    port: 4123
entity: script.tv_standby
icon: mdi:power
hold_action:
  action: toggle
```
